name: lazy_evaluation
description: Simple package to lazily evaluate objects.
version: 0.0.2
homepage: https://github.com/azilvl/lazy_evaluation

environment:
  sdk: '>=2.7.0 <3.0.0'

#dependencies:
#  path: ^1.6.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.9.4

dependencies:
