name: lazy_evaluation
description: A simple package to cache and lazily evaluate objects that have a
  expensive initialization process.
version: 1.0.0
homepage: https://github.com/azilvl/lazy_evaluation

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.17.2
