name: lazy_evaluation
description: A simple package to cache and lazily evaluate objects that have a costly initialization process. 
version: 0.0.4+1
homepage: https://github.com/azilvl/lazy_evaluation

environment:
  sdk: '>=2.7.0 <3.0.0'

#dependencies:
#  path: ^1.6.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.9.4

dependencies:
